### ISSUE TITLE
File input globbing does not work correctly for relative paths

### ISSUE THREAD

**Issue by djaglowski** [observIQ/stanza#133]
This config will output logs from `./test/specific.log`. It appears the issue is `filepath.Glob()` returns a path of the form `test/specific.log`, which does not match `./test/specific.log`

```yaml
- type: file_input
  include: 
    - './test/*.log'
  exclude: 
    - './test/specific.log'
- type: stdout
```
