### ISSUE TITLE
Plugin parameter validation fails when using scientific notation

### ISSUE THREAD

**Issue by camdencheek** [observIQ/stanza#135]
Large numbers are marshalled in scientific notation (e.g. `1e9`), which when unmarshalled with the `yaml` package to an `interface{}`, yields a `float64`. This is problematic with our parameter validation code because it errors when `1e9` is specified as the value of a parameter with the `int` type. 

A small, reproducing example: 
```yaml
# config.yaml
pipeline:
  - type: my_plugin
    test_int: 1e9

  - type: stdout
```
```yaml
# plugins/my_plugin.yaml
parameters:
  test_int:
    required: true
    type: int

pipeline:
  - type: generate_input
    count: {{ .test_int }}
```
```
❯ stanza -c ./config.yaml --plugin_dir ./plugins 2>&1  | jq
{
  "level": "error",
  "timestamp": "2020-10-02T10:50:21.594-0400",
  "message": "Failed to build agent",
  "error": "build operator configs: failed to render plugin config: plugin parameter failed validation: {\"error_message\":\"parameter must be an integer\",\"plugin_parameter\":\"test_int\",\"plugin_type\":\"my_plugin\"}"
}
```
