### ISSUE TITLE
Conditional parsing without branching graph

### ISSUE THREAD

**Issue by camdencheek** [observIQ/stanza#170]
A fairly common situation when parsing logs is "parse a message as regex if a condition is true". This is currently possible with the router operator, which can route based on the evaluation of an expression, but it significantly increases the complexity of a pipeline for what should be a pretty simple operation.

Currently, it can be done like this:
```yaml
- type: router
  routes: 
    - expr: "your boolean expression here"
      output: regex_parser
    - expr: "true"
      output: next_output
- type: regex_parser
  regex: .*
  output: next_output
```

This proposal would add an argument to relevant parsers that allows the parser to be skipped based on an expression condition. The above configuration could be simplified to something like this:
```yaml
- type: regex_parser
  regex: .*
  if: "your boolean expression here"
  output: next_output
```

Operator candidates:
- JSON parser
- Regex parser
- Severity Parser
- Time parser
- Syslog parser
- Metadata
- Rate limit?
- Restructure
- Host metadata
- Kubernetes metadata
