### ISSUE TITLE
Parsers clobber string record with a map even when `preserve` is set

### ISSUE THREAD

**Issue by camdencheek** [observIQ/stanza#185]
Our parsers (notably JSON and Regex) currently write their parsed keys as a map to the root of the record by default. The write operation is a map merge that clobbers any strings that now need to be maps. 

For example:
```yaml
pipeline:
  - type: generate_input
    count: 1
    entry:
      record: INFO test
  - type: regex_parser
    regex: '^(?P<sev>[A-Z]+)'
    preserve: true
  - type: stdout
```

Output: 
```json
{
  "timestamp": "2020-10-30T15:01:28.036774-04:00",
  "severity": 0,
  "record": {
    "sev": "INFO"
  }
}
```

It's unxpected that when `preserve: true` is set, the original message isn't available because it has been overwritten by the parsed keys. 

Workaround 1: capture the whole message as a key
```yaml
pipeline:
  - type: generate_input
    count: 1
    entry:
      record: INFO test
  - type: regex_parser
    regex: '^(?P<original>(?P<sev>[A-Z]+).*)$'
  - type: stdout
```

Workaround 2: move the original to a sub-key, then parse
```yaml
pipeline:
  - type: generate_input
    count: 1
    entry:
      record: INFO test
  - type: restructure
    ops:
      - move:
          from: $record
          to: original
  - type: regex_parser
    regex: '^(?P<sev>[A-Z]+)'
    parse_from: original
    preserve: true
  - type: stdout
```

Potential solutions:
- When `preserve` is set, move the original to a new location before overwriting it
- Parse directly to labels by default to avoid clobbering the record root
