### ISSUE TITLE
Syslog parser does not work for VMWare ESXI syslogs

### ISSUE THREAD

**Issue by camdencheek** [observIQ/stanza#218]
**Describe the bug**
The syslog parser fails on this log because it is missing a version number. The log does not conform to rfc3164 or rfc5424, but we should ideally still offer a way to parse it. 

`<167>2020-11-23T19:01:51.316Z esxi-dev-0 Rhttpproxy: verbose rhttpproxy[2475368] [Originator@6876 sub=Proxy Req 81133] Resolved endpoint : [N7Vmacore4Http16LocalServiceSpecE:0x000000126c573950] _serverNamespace = /vpxa action = Allow _port = 8089`

Config:
```yaml
pipeline:
  - type: tcp_input
    listen_address: 0.0.0.0:5140
  - type: syslog_parser
    protocol: rfc5424
  - type: stdout
```

```bash
echo "<167>2020-11-23T19:01:51.316Z esxi-dev-0 Rhttpproxy: verbose rhttpproxy[2475368] [Originator@6876 sub=Proxy Req 81133] Resolved endpoint : [N7Vmacore4Http16LocalServiceSpecE:0x000000126c573950] _serverNamespace = /vpxa action = Allow _port = 8089" | nc localhost 5140
```
