### ISSUE TITLE
Recombine operator

### ISSUE THREAD

**Issue by camdencheek** [observIQ/stanza#220]
Due to the way some platforms save logs, in some cases multiline logs are split across multiple messages. A prime example is the [CRI logging format](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md#proposed-solution), which adds metadata to each log line, but provides a flag to indicate whether the given line is part of a multiline message. In the following lines, a `F` indicates the end of a log, and a `P` indicates a log that continues to the next line:
```
2016-10-06T00:17:09.669794202Z stdout F The content of the log entry 1
2016-10-06T00:17:10.113242941Z stdout P First line of log entry 2
2016-10-06T00:17:10.113242941Z stdout P Second line of the log entry 2
2016-10-06T00:17:10.113242941Z stdout F Last line of the log entry 2
```

Currently, there is no way to parse the message out of multiple lines and combine them into a single log, so it's currently impossible to parse these logs correctly. 

This would be possible if we added a `recombine` operator which took a stream of logs and combined them into single logs based on a given set of rules. This design is not complete, nor are the edge cases thought out, but one example of how this could be done is something like the following:

```yaml
pipeline:
  - type: stdin
  - type: regex
    regex: '^(?P<timestamp>[^\s]+)\s(?P<stream>\w+)\s(?P<partial>\w)\s(?P<message>.*)\s*$'

  - type: recombine
    keep_until: '$record.partial == "F"' # could also do 'keep_while' instead
    combine_fields: # could also be called 'concatenate_fields' instead
      - '$record.message'
    overwrite_with: oldest # options are "oldest" or "newest"
    max_lines: 1000 # some sort of protection for bad patterns

  - type: stdout
```

The output logs would then look like this:
```json
{
  "timestamp": "2016-10-06T00:17:09.669Z",
  "record": {
    "stream": "stdout",
    "partial": "F",
    "message": "The content of the log entry 1"
  }
}
{
  "timestamp": "2016-10-06T00:17:10.113Z",
  "record": {
    "stream": "stdout",
    "partial": "P",
    "message": "First line of log entry 2\nSecond line of log entry 2\nLast line of log entry 2"
}
```
