### ISSUE TITLE
tcp input buffer is too small for vcenter syslog

### ISSUE THREAD

**Issue by jsirianni** [observIQ/stanza#255]
**Describe the bug**

While working with the [vcenter plugin](https://github.com/observIQ/stanza-plugins/blob/master/plugins/vmware_vcenter.yaml) (latest release, 0.0.5), I see the following error. This happens when I upgrade my vCenter appliance from 6.7 to version 7.0.

I send logs to Google Cloud, and they look fine. I worry that some logs are getting dropped.

```
{"level":"error","timestamp":"2021-02-26T14:31:44.566-0500","message":"Scanner error","operator_id":"$.vmware_vcenter.vcenter_input","operator_type":"tcp_input","error":"bufio.Scanner: token too long"}
```

My assumption is that vcenter 6.7 produced syslog messages that fit within the default buffer, and that 7.0 has messages that are too large.

**To Reproduce**

1. Setup vcenter with tls. Use vcenter 7.0. Use Stanza 0.14.15.
```
pipeline:
- type: vmware_vcenter
  listen_address: "0.0.0.0:5142"
  enable_tls: true
  certificate_file: "/opt/tls/stanza.bluemedora.localnet.crt"
  private_key_file: "/opt/tls/stanza.bluemedora.localnet.key"
  output: google
- id: google
  type: google_cloud_output
  project_id: <redacted>
  credentials_file: "/opt/observiq/stanza/log_credentials.json"
```

**Expected behavior**

Stanza should handle the log message
